[package]
name = "coat"
version = "0.1.0"
authors = ["Leopold Luley <git@leopoldluley.de>"]
edition = "2018"

[lib]
name = "coat"
path = "src/lib.rs"

[[bin]]
name = "coat-test"
path = "src/main.rs"

[dependencies.druid-shell]
version = "0.7.0"
default-features = false
features = ["x11"]
